---
language: node_js
node_js:
  - "0.12"

sudo: false

branches:
  only:
    - master # otherwise pull requests get built twice

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-data-beta.18
  - EMBER_TRY_SCENARIO=ember-data-beta.19
  - EMBER_TRY_SCENARIO=ember-data-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-data-canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm run legacy
  - ember try $EMBER_TRY_SCENARIO test --skip-cleanup
